pipeline {
    agent any
    triggers {
        pollSCM('*/30 * * * *')
    }
    // Keep the 10 most recent builds
    options { buildDiscarder(logRotator(numToKeepStr: '10')) }

    stages {
        stage('Code pull') {
            steps {
                checkout scm
            }
        }
        stage('Tests') {
            parallel {
                stage('Tests on Python 2.7') {
                    agent {
                        dockerfile {
                            filename 'ci/Dockerfile'
                            additionalBuildArgs  '--build-arg PYTHON_VERSION=2.7'
                        }
                    }
                    stages {
                        stage('Unit test') {
                            steps {
                                sh 'make unittests'
                            }
                        }
                    }
                    post {
                        success {
                            publishHTML target: [
                                allowMissing: false,
                                alwaysLinkToLastBuild: false,
                                keepAll: true,
                                reportDir: 'cover',
                                reportFiles: 'index.html',
                                reportName: 'Coverage report Python 2.7'
                            ]
                        }
                    }
                }
                stage('Tests on Python 3.6') {
                    agent {
                        dockerfile {
                            filename 'ci/Dockerfile'
                            additionalBuildArgs  '--build-arg PYTHON_VERSION=3.6'
                        }
                    }
                    stages {
                        stage('Unit test') {
                            steps {
                                sh 'make unittests'
                            }
                        }
                    }
                    post {
                        success {
                            publishHTML target: [
                                allowMissing: false,
                                alwaysLinkToLastBuild: false,
                                keepAll: true,
                                reportDir: 'cover',
                                reportFiles: 'index.html',
                                reportName: 'Coverage report Python 3.6'
                            ]
                        }
                    }
                }
            }
        }
    }
    post {
        failure {
            echo 'Something went wrong'
        }
    }
}